### ISSUE TITLE
"Cannot 

### ISSUE THREAD

**Issue by locks** [stefanpenner/ember-console#8]
Debug:

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.14.0-beta.3
DEBUG: Ember Data : 2.13.1
DEBUG: -------------------------------
```

Log:
<details>
  <summary>TypeError: Cannot convert a Symbol value to a string</summary>

```
> app.instance
TypeError: Cannot convert a Symbol value to a string
    at Object.get (/Users/ricardomendes/src/--ember/ember-cli-developer-tools/dist/assets/vendor/ember/ember.debug.js:9750:1)
    at formatValue (util.js:362:37)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at Object.inspect (util.js:203:10)
    at REPLServer.self.writer (repl.js:459:19)
    at finish (repl.js:584:38)
    at REPLServer.defaultEval (repl.js:377:5)
    at bound (domain.js:280:14)
    at REPLServer.runBound (domain.js:293:12)
    at REPLServer.eval (/Users/ricardomendes/src/--ember/ember-cli-developer-tools/node_modules/await-outside/index.js:136:29)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:241:10)
    at REPLServer.Interface._line (readline.js:590:8)
    at REPLServer.Interface._ttyWrite (readline.js:869:14)
    at REPLServer.self._ttyWrite (repl.js:609:7)
    at ReadStream.onkeypress (readline.js:120:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:194:7)
    at emitKeys (internal/readline.js:402:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:980:36)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at ReadStream.Readable.push (_stream_readable.js:136:10)
    at TTY.onread (net.js:561:20)
```
</details>

**Comment by stefanpenner** [comment]
This is a bug in node, where it can't print a Symbol. Not much we can do from our side.

**Comment by stefanpenner** [comment]
If you can open an issue with node, and provide a quick reproduction of a object \w symbol trying to be presented in the repl. That would be handy.

**Comment by stefanpenner** [comment]
I believe the issue is here: https://github.com/nodejs/node/blob/master/lib/util.js#L277

**Comment by stefanpenner** [comment]
https://github.com/nodejs/node/blob/master/lib/util.js#L349 more specifically I think

**Comment by stefanpenner** [comment]
Funky issue:

crashes: `app.instance.__container__.factoryManagerCache['router:main']`
works: `app.instance.__container__.factoryManagerCache['router:main'].class`
works: `app.instance.__container__.factoryManagerCache['router:main'].create`

I wonder if it is something related to `factoryManager` being proxies in development...

**Comment by stefanpenner** [comment]
Yup, it appears to be related to the proxy. Disabling it fixes the issue.

**Comment by chadhietala** [comment]
Likely this. https://github.com/emberjs/ember.js/blob/master/packages/container/lib/container.js#L193

**Comment by stefanpenner** [comment]
`Symbol(Symbol.toStringTag)` + `toString` missing are likely the issue

**Comment by stefanpenner** [comment]
also apparently: `Symbol(util.inspect.custom)`

**Comment by stefanpenner** [comment]
and apparently also apparently... `inspect`

**Comment by stefanpenner** [comment]
After debugging, I don't think this is an issue with nodes inspect. Although it could be improved, the issue is in ember debug proxy.
